services:
  ubuntu:
    image: ubuntu:latest
    container_name: test
    #volumes:
    #  - test.txt:/test.txt
    restart: unless-stopped
  configs:
    - source: test_config
      target: /test.txt
configs:
  test_config:
  file: test.txt